window.BADMINTON_SCHEMA = {
  title: "Badminton Motion-Analysis Product Survey",
  version: "2026-07-11-product-survey",
  sectionDescriptions: {
    "Section 4: Product Concept Interest": "Our idea is to use a wearable motion sensor attached to the elbow to analyze your badminton performance. The system may compare your movement with skilled players and provide feedback such as technique scores, consistency, wrist speed, and training suggestions."
  },
  questions: [
    { id: "level", section: "Section 1: Backgrounds", label: "What is your current badminton skill level?", type: "single_choice", required: true, allowOther: true, options: ["Beginner", "Intermediate", "Advanced", "Competitive / Club / School Team", "Coach / Assistant Coach", "Not sure"] },
    { id: "frequency", section: "Section 1: Backgrounds", label: "How often do you usually play badminton?", type: "single_choice", required: true, allowOther: true, options: ["Less than once per month", "1–3 times per month", "Once per week", "2–3 times per week", "4+ times per week"] },
    { id: "playing_purpose", section: "Section 1: Backgrounds", label: "What is your main purpose for playing badminton?", type: "multiple_choice", required: true, allowOther: true, options: ["Casual exercise", "Playing with friends", "Improving my skills", "Competition / Club / School Team training", "Fitness and health", "Social activity"] },
    { id: "pain_points", section: "Section 2: Training Pain Points", label: "What are your biggest difficulties when trying to improve your badminton technique?", type: "multiple_choice", required: true, allowOther: true, options: ["I don’t care about technique improvement", "I feel my movement is correct, but the result is not good", "I am not sure whether I am improving", "It is hard to copy the technique of advanced players", "I do not know how to practice effectively on my own", "I do not have clear training data or progress records"] },
    { id: "improvement_judgment", section: "Section 2: Training Pain Points", label: "How do you currently judge whether your stroke technique is improving?", type: "multiple_choice", required: true, allowOther: true, options: ["By feeling", "By shuttle flight result", "Coach feedback", "Friend feedback", "Video review", "Match performance / game result", "I do not have a clear method"] },
    { id: "solo_practice_difficulty", section: "Section 2: Training Pain Points", label: "When practicing without a coach, what do you find most difficult?", type: "multiple_choice", required: true, allowOther: true, options: ["I do not know what to focus on", "I cannot tell if my movement is correct", "I do not know how to fix mistakes", "I lack motivation or structure", "I cannot track my progress", "I rarely practice without a coach"] },
    { id: "training_methods", section: "Section 3: Current Training Methods", label: "What tools or methods do you currently use to improve your badminton skills?", type: "multiple_choice", required: true, allowOther: true, options: ["Coach lessons", "Watching online tutorials", "Watching professional players", "Recording videos of myself", "Asking friends for feedback", "Training with a club / team", "Practicing drills by myself", "I do not use any specific method"] },
    { id: "usual_feedback", section: "Section 3: Current Training Methods", label: "What kind of feedback do you usually want to receive?", type: "multiple_choice", required: true, allowOther: true, options: ["Technical feedback from a coach", "Suggestions from friends or teammates", "Video-based feedback", "Self-feeling during practice or match", "I rarely receive any feedback"] },
    { id: "current_satisfaction", section: "Section 3: Current Training Methods", label: "How satisfied are you with your current way of improving badminton skills?", type: "single_choice", required: true, allowOther: false, options: ["Very satisfied", "Somewhat satisfied", "Neutral / Not sure", "Somewhat dissatisfied", "Very dissatisfied"] },
    { id: "product_interest", section: "Section 4: Product Concept Interest", label: "How interested would you be in this type of badminton motion-analysis product?", type: "single_choice", required: true, allowOther: false, options: ["Very interested", "Somewhat interested", "Neutral / Not sure", "Not very interested", "Not interested at all"] },
    { id: "useful_features", section: "Section 4: Product Concept Interest", label: "Which product features would be most useful to you?", type: "multiple_choice", required: true, allowOther: true, options: ["Overall technique score", "Stroke-by-stroke analysis", "Consistency score", "Wrist speed / swing speed", "Comparison with skilled players", "Simple training suggestions", "Long-term progress charts"] },
    { id: "desired_feedback", section: "Section 4: Product Concept Interest", label: "What kind of feedback would you most want to receive?", type: "multiple_choice", required: true, allowOther: true, options: ["Whether my movement is technically correct", "How my movement differs from skilled players", "Which part of my stroke needs improvement", "Which stroke was my best", "How stable or consistent my movement is", "How I should practice next"] },
    { id: "usage_timing", section: "Section 4: Product Concept Interest", label: "When would you most likely use this type of product?", type: "multiple_choice", required: true, allowOther: true, options: ["During self-practice", "During coaching sessions", "After training for review", "When learning a new stroke", "Before or after matches", "I am not sure", "I would not use this type of product, because: ____"] },
    { id: "product_concerns", section: "Section 4: Product Concept Interest", label: "What are your biggest concerns about this type of product?", type: "multiple_choice", required: true, allowOther: true, options: ["Accuracy", "Hard to understand the feedback", "Wearing a device may be inconvenient", "The device may affect my swing or playing feeling", "Price", "I would rather ask a coach", "Data privacy", "I am not interested in training data"] },
    { id: "comments", section: "Section 6: Open Feedback & Follow-up", label: "Do you have any suggestions or comments about this idea?", type: "long_text", required: false, allowOther: false, options: [] },
    { id: "follow_up_willingness", section: "Section 6: Open Feedback & Follow-up", label: "Would you be willing to join a short follow-up interview or future product test?", type: "single_choice", required: true, allowOther: false, options: ["Yes", "Maybe", "No"] },
    { id: "contact", section: "Section 6: Open Feedback & Follow-up", label: "If yes or maybe, please leave your contact information.", description: "Your contact information will only be used for follow-up interviews or future product testing.", type: "contact", required: false, allowOther: false, options: [] }
  ]
};

